# .woodpecker.yml

# Workflow-level gate: run ONLY on main, and ONLY for push/manual (no pull_request).
when:
  branch: main
  event: [push, manual]

steps:
  deps:
    image: node:20-bullseye
    commands:
      - corepack enable
      - yarn install --frozen-lockfile
      - npx expo customize tsconfig.json
      # Default manual params (Woodpecker manual runs pass variables as env vars)
      - 'echo "BUILD_TYPE=${BUILD_TYPE:-both}  APP_ENV=${APP_ENV:-development}"'
    environment:
      # Put yarn cache somewhere explicit (optional)
      YARN_CACHE_FOLDER: /tmp/yarn-cache

  typecheck:
    image: node:20-bullseye
    depends_on: [deps]
    commands:
      - yarn typecheck

  build_debug:
    image: ghcr.io/cirruslabs/android-sdk:34
    depends_on: [typecheck]
    when:
      # Run on push OR manual with debug/both (default to both if unset)
      - evaluate: 'CI_PIPELINE_EVENT != "manual" || BUILD_TYPE == "" || BUILD_TYPE == "debug" || BUILD_TYPE == "both"'
    commands:
      # Ensure Node 20 exists in the Android image (optimize by using a custom pre-baked image)
      - apt-get update
      - apt-get install -y --no-install-recommends curl ca-certificates git
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y --no-install-recommends nodejs
      - corepack enable

      - export APP_ENV="${APP_ENV:-development}"

      - npx expo prebuild --platform android --no-install
      - cd android
      - chmod +x ./gradlew
      - ./gradlew assembleDebug --no-daemon
      - ls -lah app/build/outputs/apk/debug || true
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError"'
      # Keeps gradle stuff inside the workspace (helps within a single run; for cross-run cache use volumes)
      GRADLE_USER_HOME: .gradle

  build_release:
    image: ghcr.io/cirruslabs/android-sdk:34
    depends_on: [typecheck]
    when:
      - evaluate: 'CI_PIPELINE_EVENT == "manual" && (BUILD_TYPE == "release" || BUILD_TYPE == "both")'
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends curl ca-certificates git
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y --no-install-recommends nodejs
      - corepack enable

      - export APP_ENV="${APP_ENV:-development}"

      - npx expo prebuild --platform android --no-install

      - |
        if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/release.keystore
        fi

      - cd android
      - chmod +x ./gradlew
      - ./gradlew assembleRelease --no-daemon
      - ls -lah app/build/outputs/apk/release || true
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx4g -XX:+HeapDumpOnOutOfMemoryError"'
      GRADLE_USER_HOME: .gradle

      ANDROID_KEYSTORE_BASE64:
        from_secret: ANDROID_KEYSTORE_BASE64
      ANDROID_KEYSTORE_PASSWORD:
        from_secret: ANDROID_KEYSTORE_PASSWORD
      ANDROID_KEY_ALIAS:
        from_secret: ANDROID_KEY_ALIAS
      ANDROID_KEY_PASSWORD:
        from_secret: ANDROID_KEY_PASSWORD
